### ISSUE TITLE
The data is loading but is not ready yet...

### ISSUE THREAD

**Issue by SirCaveman** [tsebring/ArkBot#14]
Hi!

Great tool! I'm excited to see where this one goes :) 

I have a little issue though... most commands don't seem to work, for example: !players gives this:
The data is loading but is not ready yet...

I have linked my steam and such, !whoami works, so it must be something with the folder setup maybe.... although im linking correctly to the savegame files..
![bot_console](https://cloud.githubusercontent.com/assets/24266051/26030000/b0918956-3844-11e7-96a6-9e028235f41d.PNG)

And my [console.json](https://pastebin.com/tNMv8BNz)

So for the files, I downloaded https://www.myget.org/F/tsebring/api/v2/package/ArkDiscordBot and placed it in a folder under this: https://github.com/tsebring/ArkBot.git   

What am I doing wrong??

**Comment by tsebring** [comment]
Looks like something fails during extraction of cluster data and it never gets to the stage where it loads the data into memory. You can check the logs directory for any clues. That particular method is running an external tool so the error handling and logging are not exactly great.

It is possible it has something to do with the map chrystalisles and ark-tools, that combination has not been tested. Ark-tools (and single server) code is being phased out and will be removed in the future. But it is not ready yet.

**Comment by Hendrik83** [comment]
I had the same problem but with removing the database and json files in ark-tools-data it started acting different.
Now it says "we have no record of you playing in the last month." for commands.

![arkdiscordbot](https://cloud.githubusercontent.com/assets/60172/26142696/09278864-3ae2-11e7-8485-d3ebe6801d7f.PNG)
![arkdiscordbot2](https://cloud.githubusercontent.com/assets/60172/26142703/0d7d2798-3ae2-11e7-840c-476658f888c7.PNG)

This are my logfiles
https://hastebin.com/izasexuruc.xml
https://hastebin.com/xuweledosi.css

**Comment by tsebring** [comment]
The database that you removed is where steam-id linking and played time is stored.

**Comment by Hendrik83** [comment]
But after a couple of days and hours of game time it is still telling me i haven't played for the last month.

**Comment by tsebring** [comment]
Could be due to a bug with the !played time updates that were fixed in one of my recent commits. The application queries server status and online players at an interval and this would get stuck with a broken connection to the steamworks api.

If you try the newest version are you still getting the same issue?

**Comment by Hendrik83** [comment]
Is it possible for this program to lock the .ark file?
When i installed the new version and started it was running for a short while until it crashed.
Then i tried to restart it said my filepath to theisland.ark was missing.
It was still there but it changed to theisland.tmp.

**Comment by tsebring** [comment]
I'm not sure I understand. We cannot lock the file since it is used by the running server instance.

The current setup is to fail if the server is attempting to write to the file at the same time as the application. All work extracting data is preceded by a task copying all involved files to a temporary directory in order to interfere with the server as little as possible.

In the future I want it to automatically retry failed updates, but that is not a feature we have yet.

If the .ark file was renamed then something else must have renamed it. It is possible it could be something that ark-tools does, but nothing that I am aware of. Are there any logs for the crash you had?

**Comment by Hendrik83** [comment]
I do not know what was going wrong. It was doing all the things like connecting to discord and parsing the json files then stopped responding. After stopping it i restarted and it could not find the files anymore.
I needed to stop the server so it changed the .tmp file to .ark.

This build is giving more errors than usual.  And still says "we have no record of you playing in the last month".
https://pastebin.com/PabRWzUe

**Comment by tsebring** [comment]
There is nothing inherently wrong in that log file. The crash is not there.

"Failed to update server" will happen once in a while if the ark server is using one of the files at the same time the update is happening. In my experience, it does not happen a lot and as such have not been a priority.

"we have no record of you playing in the last month" is not an issue with the build. It is due to the ark-tools not being updated for the new ARK patch. Completely replacing ark-tools with a .net version is my current focus and that will take care of the issue. Much of the data that is currently unavailable through discord commands can be found in the web-app.

There is another issue with the online player list from steamworks api not containing steamids that result in some players that have multiple steam names not ever being identified as online, but that does not seem to be the case for you.

There are many things to improve but time is limited.

**Comment by Hendrik83** [comment]
Qowyn just released an updated version today that works again.

**Comment by tsebring** [comment]
Great if the updated version solves some of the problems. The one included with the application is heavily modified from the original so there could still be other problems but they will eventually be fixed.

**Comment by Hendrik83** [comment]
Yes so far i found that !checkfood and kibble from !myresources is not working anymore.
