### ISSUE TITLE
Only show authenticated profile

### ISSUE THREAD

**Issue by Hendrik83** [tsebring/ArkBot#17]
Hi, 

Can you make an option to only show the profile of the authenticated steam id.
For pvp servers you don't want people to know your characters or dino locations.

Thanks

**Comment by tsebring** [comment]
I intend to have this implemented as role based access control for specific features in the future. Authentication was the first step towards this.

**Comment by tsebring** [comment]
This is now supported in ba4cb9483b4741928b6756e9f1f257dafb391463.

**config.json**
```json
  "userRoles": {
    "admin": [ "steamid1" ]
  },
  "accessControl": {
  	"pages": {
		  "home": [ "guest" ],
		  "server": [ "guest" ],
		  "player": [ "self" ],
		  "admin-server": [ "admin" ]
  	},
  	"home": {
  		"myprofile": [ "user" ],
		  "serverlist": [ "guest" ],
		  "serverdetails": [ "guest" ],
		  "online": [ "guest" ],
		  "externalresources": [ "guest" ]
  	},
  	"server": {
	  	"players": [ "guest" ],
	  	"tribes": [ "guest" ]
  	},
  	"player": {
		  "profile": [ "guest" ],
		  "profile-detailed": [ "self" ],
		  "creatures": [ "guest" ],
		  "creatures-basestats": [ "self" ],
		  "creatures-cloud": [ "guest" ],
		  "breeding": [ "self" ],
		  "crops": [ "self" ],
		  "generators": [ "self" ],
		  "kibbles-eggs": [ "self" ],
		  "tribelog": [ "self" ]
  	},
  	"admin-server": {
	  	"players": [ "admin" ],
	  	"tribes": [ "admin" ],
	  	"structures": [ "admin" ],
	  	"structures-rcon": [ "admin" ]
  	}
  },
```

**Comment by Hendrik83** [comment]
Thanks,  could tou do something about the memory usage?  Its using close to 5 gb last version i checked.  But with growing memory usage from ark servers 5 gb is to much to use on the same server.

**Comment by tsebring** [comment]
Server updates require a lot of memory because there can be millions of objects/properties in a savegame. After an update is completed the memory is returned to the system.

The application may still appear to have a high memory usage, but the memory should be freed by the .NET runtime whenever it is needed or the garbage collector decides it is a good time to do so.

With that in mind, there are some performance and memory improvements in 25e41e77bdaf4e720d699cbc018a7770e6fe5df7 in addition to a bugfix which was stopping the GC from forcefully running after each completed update.
