### ISSUE TITLE
Features missing or disabled?

### ISSUE THREAD

**Issue by Morpheusxeno** [tsebring/ArkBot#18]
First of all thank you. Having the ability to send rcon commands through discord to the server is fantastic. I appreciate your development on this project, however, this is many things disabled, or not working that I dont understand. I understand the project is under heavy development.

How were you able to acquire this information 
https://cloud.githubusercontent.com/assets/408350/26307865/044f849a-3ef7-11e7-930f-9ac829e58d45.png

and why are so many commands disabled? How do i enable them.

**Comment by tsebring** [comment]
Discord does not offer a lot of flexibility in formatting large amounts of information. The markdown support is terrible and other options are missing. To get around this a web-app was built, which is what you see in the screenshot.

When the bot was refactored to support multiple servers all Discord commands needed to be updated or disabled. The decision was made to disable all commands that are better implemented in the web-app because it saves development time. Short term by not updating the commands to work with multiple servers, and long term by not needing to support that code over time.

If there were more developers contributing to the project the reality might look different.


**Settings to enable the web-app**

Both ports (60001 and 80) must be open externally and available for the bot to bind locally.

```json
  "webApiListenPrefix": "http://+:60001/",
  "webAppListenPrefix": "http://+:80/",
```
**Ideally you should enable SSL to protect from cookie hijacking**

This process may be more complicated than getting the web-app up and running. It can be quite hard to do without having knowledge of the processes and tools involved.

With the settings below the bot will attempt to communicate with https://letsencrypt.org/ to issue a free SSL-certificate for your domain.
For the SSL-certificate to be issued you need to prove that you control the domain name; the domain must be pointed to your server ip and port 80 must be open externally and available for the bot to bind locally.

Any errors will appear in the bot console and log files. If the process is successfull to bot will continue booting up like normal. The issued SSL-certificate is valid for 90 days after which the process needs to be repeated. 

In the configuration below you should change password, email and domains. You may use useCompatibilityNonSNIBindings=false if your OS supports SNI bindings (IIS8/Windows Server 2012, Windows 8 etc). The bot will use netsh to setup these bindings (https://technet.microsoft.com/en-us/library/bb490939.aspx).

```json
  "webApiListenPrefix": "https://+:60001/",
  "webAppListenPrefix": "https://+:443/",
  "webAppRedirectListenPrefix": [
    "http://+:80/"
  ],
  "ssl": {
    "enabled":  true,
    "challengeListenPrefix": "http://+:80/",
    "name": "ark-bot-ssl",
    "password": "secret123",
    "email": "youremail@yourdomain.com",
    "domains": [
      "app.yourdomain.com"
    ],
    "ports": [ 60001, 443 ],
    "useCompatibilityNonSNIBindings":  true
  },
```
